.TH SECRET 1
.SH NAME
secret \- sends files via ICMP protocol
.SH SYNOPSIS
.B secret
\fB\-r\fR \fI<file>\fR
\fB\-s\fR \fI<ip|hostname>\fR
[\fB\-l\fR]
[\fB\-o\fR]
[\fB\-v\fR]
.SH DESCRIPTION
.B secret
sends file via ICMP protocol, data are encrypted and hidden in ICMP echo request data.
.SH OPTIONS
.TP
.BR \-r \ <file>
Path to the file, that is to be sended.
.TP
.BR \-s \ <ip|hostname>
Ip/hostname of the server, to which the file should be sended.
.TP
.BR \-l
Starts program in the server mode (listener mode). Program saves incoming files. This option overides -r and -s.
.TP
.BR \-o
If programs is going to use loopback, option -o must be used.
.TP
.BR \-v
Verbose mode. Program describes which packets it is sending/receiving and other info.
.SH SUBMITTED FILES
.IP arguments.c
.IP arguments.h
.IP bit.h
.IP client.c
.IP client.h
.IP error.c
.IP error.h
.IP Makefile
.IP networking.c
.IP networking.h
.IP secret.1
.IP secret.c
.IP server.c
.IP server.h
.IP smrcka_bat.c
.IP smrcka_bat.h
